/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SellerSettingsRouteImport } from './routes/seller.settings'
import { Route as SellerReviewsRouteImport } from './routes/seller.reviews'
import { Route as SellerRegisterRouteImport } from './routes/seller.register'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerMessagesRouteImport } from './routes/seller.messages'
import { Route as SellerCustomersRouteImport } from './routes/seller.customers'
import { Route as SellerAnalyticsRouteImport } from './routes/seller.analytics'
import { Route as SellerIdRouteImport } from './routes/seller.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as DashboardWishlistRouteImport } from './routes/dashboard.wishlist'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAdvertisementsRouteImport } from './routes/admin.advertisements'
import { Route as SellerProductsAddRouteImport } from './routes/seller.products.add'
import { Route as AdminProductsAddRouteImport } from './routes/admin.products.add'
import { Route as SellerProductsEditIdRouteImport } from './routes/seller.products.edit.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SellerSettingsRoute = SellerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SellerRoute,
} as any)
const SellerReviewsRoute = SellerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SellerRoute,
} as any)
const SellerRegisterRoute = SellerRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerMessagesRoute = SellerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => SellerRoute,
} as any)
const SellerCustomersRoute = SellerCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAnalyticsRoute = SellerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SellerRoute,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SellerRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWishlistRoute = DashboardWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdvertisementsRoute = AdminAdvertisementsRouteImport.update({
  id: '/advertisements',
  path: '/advertisements',
  getParentRoute: () => AdminRoute,
} as any)
const SellerProductsAddRoute = SellerProductsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => SellerProductsRoute,
} as any)
const AdminProductsAddRoute = AdminProductsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AdminProductsRoute,
} as any)
const SellerProductsEditIdRoute = SellerProductsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => SellerProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/businesses': typeof BusinessesRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/seller': typeof SellerRouteWithChildren
  '/sellers': typeof SellersRoute
  '/services': typeof ServicesRoute
  '/wishlist': typeof WishlistRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/messages': typeof SellerMessagesRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRouteWithChildren
  '/seller/register': typeof SellerRegisterRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/admin/products/add': typeof AdminProductsAddRoute
  '/seller/products/add': typeof SellerProductsAddRoute
  '/seller/products/edit/$id': typeof SellerProductsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/businesses': typeof BusinessesRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sellers': typeof SellersRoute
  '/services': typeof ServicesRoute
  '/wishlist': typeof WishlistRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/messages': typeof SellerMessagesRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRouteWithChildren
  '/seller/register': typeof SellerRegisterRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/seller': typeof SellerIndexRoute
  '/admin/products/add': typeof AdminProductsAddRoute
  '/seller/products/add': typeof SellerProductsAddRoute
  '/seller/products/edit/$id': typeof SellerProductsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/businesses': typeof BusinessesRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/seller': typeof SellerRouteWithChildren
  '/sellers': typeof SellersRoute
  '/services': typeof ServicesRoute
  '/wishlist': typeof WishlistRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/messages': typeof SellerMessagesRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRouteWithChildren
  '/seller/register': typeof SellerRegisterRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/admin/products/add': typeof AdminProductsAddRoute
  '/seller/products/add': typeof SellerProductsAddRoute
  '/seller/products/edit/$id': typeof SellerProductsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/businesses'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/order-success'
    | '/orders'
    | '/products'
    | '/profile'
    | '/register'
    | '/seller'
    | '/sellers'
    | '/services'
    | '/wishlist'
    | '/admin/advertisements'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sellers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/wallet'
    | '/dashboard/wishlist'
    | '/product/$id'
    | '/seller/$id'
    | '/seller/analytics'
    | '/seller/customers'
    | '/seller/messages'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/register'
    | '/seller/reviews'
    | '/seller/settings'
    | '/admin/'
    | '/dashboard/'
    | '/seller/'
    | '/admin/products/add'
    | '/seller/products/add'
    | '/seller/products/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/businesses'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/login'
    | '/messages'
    | '/order-success'
    | '/orders'
    | '/products'
    | '/profile'
    | '/register'
    | '/sellers'
    | '/services'
    | '/wishlist'
    | '/admin/advertisements'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sellers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/wallet'
    | '/dashboard/wishlist'
    | '/product/$id'
    | '/seller/$id'
    | '/seller/analytics'
    | '/seller/customers'
    | '/seller/messages'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/register'
    | '/seller/reviews'
    | '/seller/settings'
    | '/admin'
    | '/dashboard'
    | '/seller'
    | '/admin/products/add'
    | '/seller/products/add'
    | '/seller/products/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/businesses'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/order-success'
    | '/orders'
    | '/products'
    | '/profile'
    | '/register'
    | '/seller'
    | '/sellers'
    | '/services'
    | '/wishlist'
    | '/admin/advertisements'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sellers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/wallet'
    | '/dashboard/wishlist'
    | '/product/$id'
    | '/seller/$id'
    | '/seller/analytics'
    | '/seller/customers'
    | '/seller/messages'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/register'
    | '/seller/reviews'
    | '/seller/settings'
    | '/admin/'
    | '/dashboard/'
    | '/seller/'
    | '/admin/products/add'
    | '/seller/products/add'
    | '/seller/products/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BusinessesRoute: typeof BusinessesRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SellerRoute: typeof SellerRouteWithChildren
  SellersRoute: typeof SellersRoute
  ServicesRoute: typeof ServicesRoute
  WishlistRoute: typeof WishlistRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seller/settings': {
      id: '/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof SellerSettingsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/reviews': {
      id: '/seller/reviews'
      path: '/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof SellerReviewsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/register': {
      id: '/seller/register'
      path: '/register'
      fullPath: '/seller/register'
      preLoaderRoute: typeof SellerRegisterRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/messages': {
      id: '/seller/messages'
      path: '/messages'
      fullPath: '/seller/messages'
      preLoaderRoute: typeof SellerMessagesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/customers': {
      id: '/seller/customers'
      path: '/customers'
      fullPath: '/seller/customers'
      preLoaderRoute: typeof SellerCustomersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/analytics': {
      id: '/seller/analytics'
      path: '/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof SellerAnalyticsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof SellerRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wishlist': {
      id: '/dashboard/wishlist'
      path: '/wishlist'
      fullPath: '/dashboard/wishlist'
      preLoaderRoute: typeof DashboardWishlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/advertisements': {
      id: '/admin/advertisements'
      path: '/advertisements'
      fullPath: '/admin/advertisements'
      preLoaderRoute: typeof AdminAdvertisementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seller/products/add': {
      id: '/seller/products/add'
      path: '/add'
      fullPath: '/seller/products/add'
      preLoaderRoute: typeof SellerProductsAddRouteImport
      parentRoute: typeof SellerProductsRoute
    }
    '/admin/products/add': {
      id: '/admin/products/add'
      path: '/add'
      fullPath: '/admin/products/add'
      preLoaderRoute: typeof AdminProductsAddRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/seller/products/edit/$id': {
      id: '/seller/products/edit/$id'
      path: '/edit/$id'
      fullPath: '/seller/products/edit/$id'
      preLoaderRoute: typeof SellerProductsEditIdRouteImport
      parentRoute: typeof SellerProductsRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsAddRoute: typeof AdminProductsAddRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsAddRoute: AdminProductsAddRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminAdvertisementsRoute: typeof AdminAdvertisementsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdvertisementsRoute: AdminAdvertisementsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardWishlistRoute: typeof DashboardWishlistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardWishlistRoute: DashboardWishlistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SellerProductsRouteChildren {
  SellerProductsAddRoute: typeof SellerProductsAddRoute
  SellerProductsEditIdRoute: typeof SellerProductsEditIdRoute
}

const SellerProductsRouteChildren: SellerProductsRouteChildren = {
  SellerProductsAddRoute: SellerProductsAddRoute,
  SellerProductsEditIdRoute: SellerProductsEditIdRoute,
}

const SellerProductsRouteWithChildren = SellerProductsRoute._addFileChildren(
  SellerProductsRouteChildren,
)

interface SellerRouteChildren {
  SellerIdRoute: typeof SellerIdRoute
  SellerAnalyticsRoute: typeof SellerAnalyticsRoute
  SellerCustomersRoute: typeof SellerCustomersRoute
  SellerMessagesRoute: typeof SellerMessagesRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerProductsRoute: typeof SellerProductsRouteWithChildren
  SellerRegisterRoute: typeof SellerRegisterRoute
  SellerReviewsRoute: typeof SellerReviewsRoute
  SellerSettingsRoute: typeof SellerSettingsRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerIdRoute: SellerIdRoute,
  SellerAnalyticsRoute: SellerAnalyticsRoute,
  SellerCustomersRoute: SellerCustomersRoute,
  SellerMessagesRoute: SellerMessagesRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerProductsRoute: SellerProductsRouteWithChildren,
  SellerRegisterRoute: SellerRegisterRoute,
  SellerReviewsRoute: SellerReviewsRoute,
  SellerSettingsRoute: SellerSettingsRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BusinessesRoute: BusinessesRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SellerRoute: SellerRouteWithChildren,
  SellersRoute: SellersRoute,
  ServicesRoute: ServicesRoute,
  WishlistRoute: WishlistRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
